services:
  claude-worktree:
    build: .
    container_name: claude-worktree
    volumes:
      # プロジェクトファイルの永続化
      - .:/claude-worktree
      - claude_config:/root/.claude
      - ./.docker/bash_history:/root/.bash_history
      - ~/.codex:/root/.codex
    environment:
      - NPM_USER
      - NPM_EMAIL
      - NPM_PASS
      # AI API Keys
      - OPENAI_API_KEY
      - ANTHROPIC_API_KEY
      # GitHub設定
      - GITHUB_TOKEN
      - GITHUB_PERSONAL_ACCESS_TOKEN
      - GITHUB_USERNAME
    stdin_open: true
    tty: true
    restart: unless-stopped
    working_dir: /claude-worktree

volumes:
  claude_config: {}
