services:
  claude-worktree:
    build: .
    container_name: claude-worktree
    volumes:
      - .:/claude-worktree
      - bash-history:/root/.bash_history_dir
      - ./.docker/bash_history:/root/.bash_history
      - claude-config:/root/.claude
      - codex-config:/root/.codex
      - ~/.codex/auth.json:/root/.codex/auth.json
    environment:
      - NPM_USER
      - NPM_EMAIL
      - NPM_PASS
      - OPENAI_API_KEY
      - ANTHROPIC_API_KEY
      - GITHUB_TOKEN
      - GITHUB_PERSONAL_ACCESS_TOKEN
      - GITHUB_USERNAME
      - HISTFILE=/root/.bash_history_dir/.bash_history
      - HISTSIZE=100000
      - HISTFILESIZE=100000
      - MAX_MCP_OUTPUT_TOKENS
      - ENABLE_BACKGROUND_TASKS=1
      - FORCE_AUTO_BACKGROUND_TASKS=1
    stdin_open: true
    tty: true
    working_dir: /claude-worktree

volumes:
  bash-history: {}
  claude-config: {}
  codex-config: {}