openapi: 3.0.0
info:
  title: Claude-Worktree CLI Interface Contract
  version: 1.0.0
  description: CLI interface specification for claude-worktree tool selection feature

paths:
  /cli/claude-worktree:
    summary: Main claude-worktree command interface
    
    get:
      operationId: claude-worktree
      summary: Launch claude-worktree with tool selection
      description: |
        Main entry point for claude-worktree command.
        Without options, shows interactive tool selection.
        With options, performs specified action.
        Supports pass-through arguments to selected tools using -- separator.
      
      parameters:
        - name: tool
          in: query
          schema:
            type: string
            enum: [claude, codex]
          description: Directly specify which tool to use
          
        - name: reset-default
          in: query
          schema:
            type: boolean
          description: Reset default tool selection
          
        - name: help
          in: query
          schema:
            type: boolean
          description: Show help information
          
        - name: version
          in: query
          schema:
            type: boolean
          description: Show version information
          
        - name: no-color
          in: query
          schema:
            type: boolean
          description: Disable colored output
          
        - name: quiet
          in: query
          schema:
            type: boolean
          description: Suppress non-essential output
          
        - name: passthrough
          in: query
          schema:
            type: array
            items:
              type: string
          description: Arguments after -- to pass to the selected tool
          examples:
            claude_resume: ["-r"]
            claude_context: ["-c"]
            codex_continue: ["--continue"]
            codex_resume: ["--resume"]
      
      responses:
        '0':
          description: Successful execution
          content:
            text/plain:
              schema:
                type: string
              examples:
                claude_success:
                  value: "✓ Claude Code workspace initialized"
                codex_success:
                  value: "✓ Codex CLI session started"
                
        '1':
          description: General error
          content:
            text/plain:
              schema:
                type: string
              examples:
                not_installed:
                  value: "Error: Codex CLI is not installed. Please install it with: npm install -g @openai/codex-cli"
                config_error:
                  value: "Error: Unable to read configuration file"
                  
        '2':
          description: Invalid usage
          content:
            text/plain:
              schema:
                type: string
              examples:
                invalid_option:
                  value: "Error: Unknown option '--invalid'"
                invalid_tool:
                  value: "Error: Invalid tool 'xyz'. Valid options are: claude, codex"
                  
        '130':
          description: User cancelled (q key or Ctrl+C)
          content:
            text/plain:
              schema:
                type: string
              examples:
                cancelled_q:
                  value: "Operation cancelled by user (q)"
                cancelled_ctrl_c:
                  value: "Operation cancelled by user (Ctrl+C)"

components:
  schemas:
    InteractivePrompt:
      type: object
      properties:
        type:
          type: string
          enum: [select]
        message:
          type: string
          example: "Which AI tool would you like to use? (Use arrow keys, press 'q' to cancel)"
        choices:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: "Claude Code"
              value:
                type: string
                example: "claude"
              description:
                type: string
                example: "Anthropic's AI coding assistant"
              disabled:
                type: boolean
                default: false
              disabledReason:
                type: string
                example: "Not installed"
        cancelKey:
          type: string
          default: "q"
          description: "Key to cancel selection"
    
    ConfigFile:
      type: object
      properties:
        version:
          type: string
          pattern: '^\d+\.\d+\.\d+$'
          example: "1.0.0"
        defaultTool:
          type: string
          enum: [claude, codex, null]
        lastSelection:
          type: string
          enum: [claude, codex, null]
        selectionHistory:
          type: array
          maxItems: 100
          items:
            type: object
            properties:
              tool:
                type: string
                enum: [claude, codex]
              timestamp:
                type: string
                format: date-time
              source:
                type: string
                enum: [interactive, cli-option, default]
              toolArgs:
                type: array
                items:
                  type: string
                description: "Arguments passed to the tool"
        preferences:
          type: object
          properties:
            rememberSelection:
              type: boolean
              default: true
            showWelcomeMessage:
              type: boolean
              default: true
            colorOutput:
              type: boolean
              default: true
        toolDefaults:
          type: object
          properties:
            claude:
              type: object
              properties:
                args:
                  type: array
                  items:
                    type: string
                  example: []
            codex:
              type: object
              properties:
                args:
                  type: array
                  items:
                    type: string
                  example: []
    
    OutputFormat:
      type: object
      properties:
        format:
          type: string
          enum: [text, json]
          default: text
        content:
          oneOf:
            - type: string
            - type: object

examples:
  commands:
    interactive:
      command: "claude-worktree"
      description: "Launch interactive tool selection (cancel with 'q' key)"
      
    directClaude:
      command: "claude-worktree --tool claude"
      description: "Launch with Claude Code directly"
      
    directCodex:
      command: "claude-worktree --tool codex"
      description: "Launch with Codex CLI directly"
      
    claudeWithResume:
      command: "claude-worktree --tool claude -- -r"
      description: "Launch Claude Code with resume option"
      
    claudeWithContext:
      command: "claude-worktree --tool claude -- -c"
      description: "Launch Claude Code with context option"
      
    codexWithContinue:
      command: "claude-worktree --tool codex -- --continue"
      description: "Launch Codex CLI with continue option"
      
    codexWithResume:
      command: "claude-worktree --tool codex -- --resume"
      description: "Launch Codex CLI with resume option"
      
    resetDefault:
      command: "claude-worktree --reset-default"
      description: "Reset default tool selection"
      
    help:
      command: "claude-worktree --help"
      description: "Show help information"
      
    version:
      command: "claude-worktree --version"
      description: "Show version information"
      
    quietMode:
      command: "claude-worktree --tool claude --quiet -- -r"
      description: "Launch Claude Code with minimal output and resume option"
      
    noColor:
      command: "claude-worktree --no-color"
      description: "Launch with plain text output"