openapi: 3.0.0
info:
  title: Worktree CLI Interface Contract
  version: 1.0.0
  description: CLI interface specification for worktree tool selection feature

paths:
  /cli/worktree:
    summary: Main worktree command interface
    
    get:
      operationId: worktree
      summary: Launch worktree with tool selection
      description: |
        Main entry point for worktree command.
        Without options, shows interactive tool selection.
        With options, performs specified action.
      
      parameters:
        - name: tool
          in: query
          schema:
            type: string
            enum: [claude, codex]
          description: Directly specify which tool to use
          
        - name: reset-default
          in: query
          schema:
            type: boolean
          description: Reset default tool selection
          
        - name: help
          in: query
          schema:
            type: boolean
          description: Show help information
          
        - name: version
          in: query
          schema:
            type: boolean
          description: Show version information
          
        - name: no-color
          in: query
          schema:
            type: boolean
          description: Disable colored output
          
        - name: quiet
          in: query
          schema:
            type: boolean
          description: Suppress non-essential output
      
      responses:
        '0':
          description: Successful execution
          content:
            text/plain:
              schema:
                type: string
              examples:
                success:
                  value: "✓ Claude Code workspace initialized"
                
        '1':
          description: General error
          content:
            text/plain:
              schema:
                type: string
              examples:
                error:
                  value: "Error: Codex CLI is not installed"
                  
        '2':
          description: Invalid usage
          content:
            text/plain:
              schema:
                type: string
              examples:
                usage:
                  value: "Error: Unknown option '--invalid'"
                  
        '130':
          description: User cancelled (Ctrl+C)
          content:
            text/plain:
              schema:
                type: string
              examples:
                cancelled:
                  value: "Operation cancelled by user"

components:
  schemas:
    InteractivePrompt:
      type: object
      properties:
        type:
          type: string
          enum: [select]
        message:
          type: string
          example: "Which AI tool would you like to use?"
        choices:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: "Claude Code"
              value:
                type: string
                example: "claude"
              description:
                type: string
                example: "Anthropic's AI coding assistant"
              disabled:
                type: boolean
                default: false
              disabledReason:
                type: string
                example: "Not installed"
    
    ConfigFile:
      type: object
      properties:
        version:
          type: string
          pattern: '^\d+\.\d+\.\d+$'
          example: "1.0.0"
        defaultTool:
          type: string
          enum: [claude, codex, null]
        lastSelection:
          type: string
          enum: [claude, codex, null]
        selectionHistory:
          type: array
          maxItems: 100
          items:
            type: object
            properties:
              tool:
                type: string
                enum: [claude, codex]
              timestamp:
                type: string
                format: date-time
              source:
                type: string
                enum: [interactive, cli-option, default]
        preferences:
          type: object
          properties:
            rememberSelection:
              type: boolean
              default: true
            showWelcomeMessage:
              type: boolean
              default: true
            colorOutput:
              type: boolean
              default: true
    
    OutputFormat:
      type: object
      properties:
        format:
          type: string
          enum: [text, json]
          default: text
        content:
          oneOf:
            - type: string
            - type: object

examples:
  commands:
    interactive:
      command: "worktree"
      description: "Launch interactive tool selection"
      
    directClaude:
      command: "worktree --tool claude"
      description: "Launch with Claude Code directly"
      
    directCodex:
      command: "worktree --tool codex"
      description: "Launch with Codex CLI directly"
      
    resetDefault:
      command: "worktree --reset-default"
      description: "Reset default tool selection"
      
    help:
      command: "worktree --help"
      description: "Show help information"
      
    version:
      command: "worktree --version"
      description: "Show version information"
      
    quietMode:
      command: "worktree --tool claude --quiet"
      description: "Launch Claude Code with minimal output"
      
    noColor:
      command: "worktree --no-color"
      description: "Launch with plain text output"